### ISSUE TITLE
error with .trk files

### ISSUE THREAD

**Issue by gelazari** [demianw/tract_querier#19]
I have my .tck file and i convert it to .vtk and .trk for testing purposes with TractConverter (https://github.com/MarcCote/tractconverter). When i execute tract_querier with using as input the .vtk file, it works, but when i use as input the .trk file, i get the following error:

Loading files
Traceback (most recent call last):
  File "/Users/glazar0/Library/Enthought/Canopy_64bit/User/bin/tract_querier", line 284, in <module>
    main()
  File "/Users/glazar0/Library/Enthought/Canopy_64bit/User/bin/tract_querier", line 139, in main
    options.tractography_file_name
  File "/Users/glazar0/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/tract_querier/tractography/__init__.py", line 46, in tractography_from_file
    return tractography_from_trackvis_file(filename)
  File "/Users/glazar0/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/tract_querier/tractography/trackvis.py", line 78, in tractography_from_trackvis_file
    tracts_and_data, header = trackvis.read(filename, points_space='rasmm')
  File "/Users/glazar0/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nibabel/trackvis.py", line 173, in read
    _check_hdr_points_space(hdr, points_space)
  File "/Users/glazar0/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nibabel/trackvis.py", line 473, in _check_hdr_points_space
    'field value %s' % (aff_zooms, zooms))

Using separately the nibabel.trackvis.read(), i can read the .trk file though. Any suggestions?

**Comment by demianw** [comment]
Yes it is a compatibility issue on the trackvis reader of Nibabel. The thing is that, in the current nibabel implementation, without the RASMM option you can read the data but not be sure of the space encoding of the tracts.

Maybe @MarcCote has an idea of how to force tractconverter to produce TRK files that are in RASMM space encoding.

--
Demian Wassermann, PhD
demian.wassermann@inria.fr
Research Scientist
Athena Project Team
INRIA Sophia Antipolis - Méditerranée 
2004 route des lucioles - FR-06902

**Comment by MarcCote** [comment]
@gelazari you did specified the option `-anat` when converting from tck to trk?

**Comment by gelazari** [comment]
Yes i did specify an anatomy to get the trk file and then i perform the tract_querier by using the same anatomy

**Comment by gelazari** [comment]
fixed it. It was just a simple scripting mistake that had nothing to do with the integrity of the used programs.

**Comment by demianw** [comment]
:D
