### ISSUE TITLE
tract_math <vtk> tract_volume <res> fails

### ISSUE THREAD

**Issue by reckbo** [demianw/tract_querier#30]
## Issue

Resolution command line argument to to tract_volume is not passed to `tensor_operations.compute_all_measures`, causing this error:

```
Traceback (most recent call last):
  File "scripts-pipeline/tractvols/tract_querier/scripts-2.7/tract_math", line 125, in <module>
    main()
  File "scripts-pipeline/tractvols/tract_querier/scripts-2.7/tract_math", line 111, in main
    tractography, *args.operation_parameters)
  File "/tmp/t/scripts-pipeline/tractvols/tract_querier/lib/tract_querier/tract_math/decorator.py", line 148, in wrapper
    process_output(func(*option_and_args))
  File "/tmp/t/scripts-pipeline/tractvols/tract_querier/lib/tract_querier/tract_math/operations.py", line 52, in tract_volume
    return tensor_operations.compute_all_measures(tractography, ['tract volume'])
  File "/tmp/t/scripts-pipeline/tractvols/tract_querier/lib/tract_querier/tract_math/tensor_operations.py", line 86, in compute_all_measures
    ordered_dict[key] = unordered_results[key]
KeyError: 'tract volume'
```

Here's the offending code.

``` python
# operations.py
@tract_math_operation('<volume unit>: calculates the volume of a tract based on voxel occupancy of a certain voxel volume')
def tract_volume(optional_flags, tractography, resolution):
    return tensor_operations.compute_all_measures(tractography, ['tract volume']) # <-- resolution should be passed in here
```
## Reproducible Steps

Run 

```
tract_math <myvtk> tract_volume 1
```

**Comment by demianw** [comment]
Thanks @reckbo ! Could you provide a link with a small example dataset please?

**Comment by reckbo** [comment]
Copy and paste this into a terminal

```
cat << EOF > t.vtk
# vtk DataFile Version 4.0
vtk output
ASCII
DATASET POLYDATA
POINTS 3 double
0 1 2
0.1 1.1 2.1
0.2 1.2 2.2
LINES 1 4
3 0 1 2
EOF
```
and then run

    tract_math t.vtk tract_volume 1

Thanks for looking into this.

**Comment by demianw** [comment]
Hi @reckbo I think that I've fixed the issue. Could you please double check such that I can close this thread?

**Comment by reckbo** [comment]
@demianw sorry it took a while but I confirmed the fix works, thanks.
